package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALL_USER_EVENT".
 */
public class AllUserEvent {

    private String name;
    private String event_date;
    private String image_url;
    private String event_desc;
    private String event_id;
    private String likecount;
    private String commentcount;
    private String event_title;
    private String eventmaster_id;
    private String eventicon;

    public AllUserEvent() {
    }

    public AllUserEvent(String name, String event_date, String image_url, String event_desc, String event_id, String likecount, String commentcount, String event_title, String eventmaster_id, String eventicon) {
        this.name = name;
        this.event_date = event_date;
        this.image_url = image_url;
        this.event_desc = event_desc;
        this.event_id = event_id;
        this.likecount = likecount;
        this.commentcount = commentcount;
        this.event_title = event_title;
        this.eventmaster_id = eventmaster_id;
        this.eventicon = eventicon;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEvent_date() {
        return event_date;
    }

    public void setEvent_date(String event_date) {
        this.event_date = event_date;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public String getEvent_desc() {
        return event_desc;
    }

    public void setEvent_desc(String event_desc) {
        this.event_desc = event_desc;
    }

    public String getEvent_id() {
        return event_id;
    }

    public void setEvent_id(String event_id) {
        this.event_id = event_id;
    }

    public String getLikecount() {
        return likecount;
    }

    public void setLikecount(String likecount) {
        this.likecount = likecount;
    }

    public String getCommentcount() {
        return commentcount;
    }

    public void setCommentcount(String commentcount) {
        this.commentcount = commentcount;
    }

    public String getEvent_title() {
        return event_title;
    }

    public void setEvent_title(String event_title) {
        this.event_title = event_title;
    }

    public String getEventmaster_id() {
        return eventmaster_id;
    }

    public void setEventmaster_id(String eventmaster_id) {
        this.eventmaster_id = eventmaster_id;
    }

    public String getEventicon() {
        return eventicon;
    }

    public void setEventicon(String eventicon) {
        this.eventicon = eventicon;
    }

}
