package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALL_USERS".
 */
public class AllUsers {

    private String name;
    private String department;
    private String designation;
    private String user_id;
    private String email;
    private String location;
    private String imageurl;
    private String coiMisAdmin;
    private String mxway;

    public AllUsers() {
    }

    public AllUsers(String name, String department, String designation, String user_id, String email, String location, String imageurl, String coiMisAdmin, String mxway) {
        this.name = name;
        this.department = department;
        this.designation = designation;
        this.user_id = user_id;
        this.email = email;
        this.location = location;
        this.imageurl = imageurl;
        this.coiMisAdmin = coiMisAdmin;
        this.mxway = mxway;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getImageurl() {
        return imageurl;
    }

    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    public String getCoiMisAdmin() {
        return coiMisAdmin;
    }

    public void setCoiMisAdmin(String coiMisAdmin) {
        this.coiMisAdmin = coiMisAdmin;
    }

    public String getMxway() {
        return mxway;
    }

    public void setMxway(String mxway) {
        this.mxway = mxway;
    }

}
