package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BULLETIN_LIST".
 */
public class BulletinList {

    private String postedbyuser;
    private String postbyemail;
    private String details;
    private String create_date;
    private String groupemail;
    private String type;
    private String fileurl;
    private String url;

    public BulletinList() {
    }

    public BulletinList(String postedbyuser, String postbyemail, String details, String create_date, String groupemail, String type, String fileurl, String url) {
        this.postedbyuser = postedbyuser;
        this.postbyemail = postbyemail;
        this.details = details;
        this.create_date = create_date;
        this.groupemail = groupemail;
        this.type = type;
        this.fileurl = fileurl;
        this.url = url;
    }

    public String getPostedbyuser() {
        return postedbyuser;
    }

    public void setPostedbyuser(String postedbyuser) {
        this.postedbyuser = postedbyuser;
    }

    public String getPostbyemail() {
        return postbyemail;
    }

    public void setPostbyemail(String postbyemail) {
        this.postbyemail = postbyemail;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public String getCreate_date() {
        return create_date;
    }

    public void setCreate_date(String create_date) {
        this.create_date = create_date;
    }

    public String getGroupemail() {
        return groupemail;
    }

    public void setGroupemail(String groupemail) {
        this.groupemail = groupemail;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getFileurl() {
        return fileurl;
    }

    public void setFileurl(String fileurl) {
        this.fileurl = fileurl;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
