package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BULLETIN_CATEGORY".
 */
public class BulletinCategory {

    private String id;
    private String name;
    private String isactive;

    public BulletinCategory() {
    }

    public BulletinCategory(String id, String name, String isactive) {
        this.id = id;
        this.name = name;
        this.isactive = isactive;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIsactive() {
        return isactive;
    }

    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

}
