package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CELEBRATION_MOMENTS".
 */
public class CelebrationMoments {

    private String userid;
    private String name;
    private String eventmaster_id;
    private String event_id;
    private String department;
    private String event_desc;
    private String work_year;
    private String imageurl;
    private String emailId;
    private String title;

    public CelebrationMoments() {
    }

    public CelebrationMoments(String userid, String name, String eventmaster_id, String event_id, String department, String event_desc, String work_year, String imageurl, String emailId, String title) {
        this.userid = userid;
        this.name = name;
        this.eventmaster_id = eventmaster_id;
        this.event_id = event_id;
        this.department = department;
        this.event_desc = event_desc;
        this.work_year = work_year;
        this.imageurl = imageurl;
        this.emailId = emailId;
        this.title = title;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEventmaster_id() {
        return eventmaster_id;
    }

    public void setEventmaster_id(String eventmaster_id) {
        this.eventmaster_id = eventmaster_id;
    }

    public String getEvent_id() {
        return event_id;
    }

    public void setEvent_id(String event_id) {
        this.event_id = event_id;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public String getEvent_desc() {
        return event_desc;
    }

    public void setEvent_desc(String event_desc) {
        this.event_desc = event_desc;
    }

    public String getWork_year() {
        return work_year;
    }

    public void setWork_year(String work_year) {
        this.work_year = work_year;
    }

    public String getImageurl() {
        return imageurl;
    }

    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
