package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COUNT_RG".
 */
public class CountRG {

    private String grecognition;
    private String rrecognition;
    private String tgrecognition;
    private String trrecognition;

    public CountRG() {
    }

    public CountRG(String grecognition, String rrecognition, String tgrecognition, String trrecognition) {
        this.grecognition = grecognition;
        this.rrecognition = rrecognition;
        this.tgrecognition = tgrecognition;
        this.trrecognition = trrecognition;
    }

    public String getGrecognition() {
        return grecognition;
    }

    public void setGrecognition(String grecognition) {
        this.grecognition = grecognition;
    }

    public String getRrecognition() {
        return rrecognition;
    }

    public void setRrecognition(String rrecognition) {
        this.rrecognition = rrecognition;
    }

    public String getTgrecognition() {
        return tgrecognition;
    }

    public void setTgrecognition(String tgrecognition) {
        this.tgrecognition = tgrecognition;
    }

    public String getTrrecognition() {
        return trrecognition;
    }

    public void setTrrecognition(String trrecognition) {
        this.trrecognition = trrecognition;
    }

}
