package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CURRENT_OPINION".
 */
public class CurrentOpinion {

    private String opinionid;
    private String question;
    private String answertype;
    private String enddate;
    private String isactive;
    private String type;

    public CurrentOpinion() {
    }

    public CurrentOpinion(String opinionid, String question, String answertype, String enddate, String isactive, String type) {
        this.opinionid = opinionid;
        this.question = question;
        this.answertype = answertype;
        this.enddate = enddate;
        this.isactive = isactive;
        this.type = type;
    }

    public String getOpinionid() {
        return opinionid;
    }

    public void setOpinionid(String opinionid) {
        this.opinionid = opinionid;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getAnswertype() {
        return answertype;
    }

    public void setAnswertype(String answertype) {
        this.answertype = answertype;
    }

    public String getEnddate() {
        return enddate;
    }

    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }

    public String getIsactive() {
        return isactive;
    }

    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
