package db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "CURRENT_OPINION".
 */
public class CurrentOpinionDao extends AbstractDao<CurrentOpinion, Void> {

    public static final String TABLENAME = "CURRENT_OPINION";

    /**
     * Properties of entity CurrentOpinion.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Opinionid = new Property(0, String.class, "opinionid", false, "OPINIONID");
        public final static Property Question = new Property(1, String.class, "question", false, "QUESTION");
        public final static Property Answertype = new Property(2, String.class, "answertype", false, "ANSWERTYPE");
        public final static Property Enddate = new Property(3, String.class, "enddate", false, "ENDDATE");
        public final static Property Isactive = new Property(4, String.class, "isactive", false, "ISACTIVE");
        public final static Property Type = new Property(5, String.class, "type", false, "TYPE");
    }

    ;


    public CurrentOpinionDao(DaoConfig config) {
        super(config);
    }

    public CurrentOpinionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"CURRENT_OPINION\" (" + //
                "\"OPINIONID\" TEXT," + // 0: opinionid
                "\"QUESTION\" TEXT," + // 1: question
                "\"ANSWERTYPE\" TEXT," + // 2: answertype
                "\"ENDDATE\" TEXT," + // 3: enddate
                "\"ISACTIVE\" TEXT," + // 4: isactive
                "\"TYPE\" TEXT);"); // 5: type
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CURRENT_OPINION\"";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, CurrentOpinion entity) {
        stmt.clearBindings();

        String opinionid = entity.getOpinionid();
        if (opinionid != null) {
            stmt.bindString(1, opinionid);
        }

        String question = entity.getQuestion();
        if (question != null) {
            stmt.bindString(2, question);
        }

        String answertype = entity.getAnswertype();
        if (answertype != null) {
            stmt.bindString(3, answertype);
        }

        String enddate = entity.getEnddate();
        if (enddate != null) {
            stmt.bindString(4, enddate);
        }

        String isactive = entity.getIsactive();
        if (isactive != null) {
            stmt.bindString(5, isactive);
        }

        String type = entity.getType();
        if (type != null) {
            stmt.bindString(6, type);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }

    /**
     * @inheritdoc
     */
    @Override
    public CurrentOpinion readEntity(Cursor cursor, int offset) {
        CurrentOpinion entity = new CurrentOpinion( //
                cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // opinionid
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // question
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // answertype
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // enddate
                cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // isactive
                cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // type
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, CurrentOpinion entity, int offset) {
        entity.setOpinionid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setQuestion(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAnswertype(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEnddate(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsactive(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Void updateKeyAfterInsert(CurrentOpinion entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Void getKey(CurrentOpinion entity) {
        return null;
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
