package db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userLoginInfoDaoConfig;
    private final DaoConfig allUserEventDaoConfig;
    private final DaoConfig userWeddingDaoConfig;
    private final DaoConfig allUsersDaoConfig;
    private final DaoConfig allWebNotificationDaoConfig;
    private final DaoConfig getMorePostDaoConfig;
    private final DaoConfig getXpresswayPostDaoConfig;
    private final DaoConfig recentActivityDaoConfig;
    private final DaoConfig commentsDaoConfig;
    private final DaoConfig xpresswayDaoConfig;
    private final DaoConfig awardDaoConfig;
    private final DaoConfig expossorDaoConfig;
    private final DaoConfig currentOpinionDaoConfig;
    private final DaoConfig pollResultDaoConfig;
    private final DaoConfig bulletinCategoryDaoConfig;
    private final DaoConfig recognitionGivenDaoConfig;
    private final DaoConfig recognitionRecievedDaoConfig;
    private final DaoConfig recognitionGivenListDaoConfig;
    private final DaoConfig recognitionRecievedListDaoConfig;
    private final DaoConfig celebrationMomentsDaoConfig;
    private final DaoConfig countRGDaoConfig;
    private final DaoConfig givenLikeDaoConfig;
    private final DaoConfig bulletinListDaoConfig;
    private final DaoConfig srijanTOPCommentDaoConfig;
    private final DaoConfig clusterDaoConfig;
    private final DaoConfig gPWALLPOSTDaoConfig;
    private final DaoConfig xPGPWALLPOSTDaoConfig;

    private final UserLoginInfoDao userLoginInfoDao;
    private final AllUserEventDao allUserEventDao;
    private final UserWeddingDao userWeddingDao;
    private final AllUsersDao allUsersDao;
    private final AllWebNotificationDao allWebNotificationDao;
    private final GetMorePostDao getMorePostDao;
    private final GetXpresswayPostDao getXpresswayPostDao;
    private final RecentActivityDao recentActivityDao;
    private final CommentsDao commentsDao;
    private final XpresswayDao xpresswayDao;
    private final AwardDao awardDao;
    private final ExpossorDao expossorDao;
    private final CurrentOpinionDao currentOpinionDao;
    private final PollResultDao pollResultDao;
    private final BulletinCategoryDao bulletinCategoryDao;
    private final RecognitionGivenDao recognitionGivenDao;
    private final RecognitionRecievedDao recognitionRecievedDao;
    private final RecognitionGivenListDao recognitionGivenListDao;
    private final RecognitionRecievedListDao recognitionRecievedListDao;
    private final CelebrationMomentsDao celebrationMomentsDao;
    private final CountRGDao countRGDao;
    private final GivenLikeDao givenLikeDao;
    private final BulletinListDao bulletinListDao;
    private final SrijanTOPCommentDao srijanTOPCommentDao;
    private final ClusterDao clusterDao;
    private final GPWALLPOSTDao gPWALLPOSTDao;
    private final XPGPWALLPOSTDao xPGPWALLPOSTDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userLoginInfoDaoConfig = daoConfigMap.get(UserLoginInfoDao.class).clone();
        userLoginInfoDaoConfig.initIdentityScope(type);

        allUserEventDaoConfig = daoConfigMap.get(AllUserEventDao.class).clone();
        allUserEventDaoConfig.initIdentityScope(type);

        userWeddingDaoConfig = daoConfigMap.get(UserWeddingDao.class).clone();
        userWeddingDaoConfig.initIdentityScope(type);

        allUsersDaoConfig = daoConfigMap.get(AllUsersDao.class).clone();
        allUsersDaoConfig.initIdentityScope(type);

        allWebNotificationDaoConfig = daoConfigMap.get(AllWebNotificationDao.class).clone();
        allWebNotificationDaoConfig.initIdentityScope(type);

        getMorePostDaoConfig = daoConfigMap.get(GetMorePostDao.class).clone();
        getMorePostDaoConfig.initIdentityScope(type);

        getXpresswayPostDaoConfig = daoConfigMap.get(GetXpresswayPostDao.class).clone();
        getXpresswayPostDaoConfig.initIdentityScope(type);

        recentActivityDaoConfig = daoConfigMap.get(RecentActivityDao.class).clone();
        recentActivityDaoConfig.initIdentityScope(type);

        commentsDaoConfig = daoConfigMap.get(CommentsDao.class).clone();
        commentsDaoConfig.initIdentityScope(type);

        xpresswayDaoConfig = daoConfigMap.get(XpresswayDao.class).clone();
        xpresswayDaoConfig.initIdentityScope(type);

        awardDaoConfig = daoConfigMap.get(AwardDao.class).clone();
        awardDaoConfig.initIdentityScope(type);

        expossorDaoConfig = daoConfigMap.get(ExpossorDao.class).clone();
        expossorDaoConfig.initIdentityScope(type);

        currentOpinionDaoConfig = daoConfigMap.get(CurrentOpinionDao.class).clone();
        currentOpinionDaoConfig.initIdentityScope(type);

        pollResultDaoConfig = daoConfigMap.get(PollResultDao.class).clone();
        pollResultDaoConfig.initIdentityScope(type);

        bulletinCategoryDaoConfig = daoConfigMap.get(BulletinCategoryDao.class).clone();
        bulletinCategoryDaoConfig.initIdentityScope(type);

        recognitionGivenDaoConfig = daoConfigMap.get(RecognitionGivenDao.class).clone();
        recognitionGivenDaoConfig.initIdentityScope(type);

        recognitionRecievedDaoConfig = daoConfigMap.get(RecognitionRecievedDao.class).clone();
        recognitionRecievedDaoConfig.initIdentityScope(type);

        recognitionGivenListDaoConfig = daoConfigMap.get(RecognitionGivenListDao.class).clone();
        recognitionGivenListDaoConfig.initIdentityScope(type);

        recognitionRecievedListDaoConfig = daoConfigMap.get(RecognitionRecievedListDao.class).clone();
        recognitionRecievedListDaoConfig.initIdentityScope(type);

        celebrationMomentsDaoConfig = daoConfigMap.get(CelebrationMomentsDao.class).clone();
        celebrationMomentsDaoConfig.initIdentityScope(type);

        countRGDaoConfig = daoConfigMap.get(CountRGDao.class).clone();
        countRGDaoConfig.initIdentityScope(type);

        givenLikeDaoConfig = daoConfigMap.get(GivenLikeDao.class).clone();
        givenLikeDaoConfig.initIdentityScope(type);

        bulletinListDaoConfig = daoConfigMap.get(BulletinListDao.class).clone();
        bulletinListDaoConfig.initIdentityScope(type);

        srijanTOPCommentDaoConfig = daoConfigMap.get(SrijanTOPCommentDao.class).clone();
        srijanTOPCommentDaoConfig.initIdentityScope(type);

        clusterDaoConfig = daoConfigMap.get(ClusterDao.class).clone();
        clusterDaoConfig.initIdentityScope(type);

        gPWALLPOSTDaoConfig = daoConfigMap.get(GPWALLPOSTDao.class).clone();
        gPWALLPOSTDaoConfig.initIdentityScope(type);

        xPGPWALLPOSTDaoConfig = daoConfigMap.get(XPGPWALLPOSTDao.class).clone();
        xPGPWALLPOSTDaoConfig.initIdentityScope(type);

        userLoginInfoDao = new UserLoginInfoDao(userLoginInfoDaoConfig, this);
        allUserEventDao = new AllUserEventDao(allUserEventDaoConfig, this);
        userWeddingDao = new UserWeddingDao(userWeddingDaoConfig, this);
        allUsersDao = new AllUsersDao(allUsersDaoConfig, this);
        allWebNotificationDao = new AllWebNotificationDao(allWebNotificationDaoConfig, this);
        getMorePostDao = new GetMorePostDao(getMorePostDaoConfig, this);
        getXpresswayPostDao = new GetXpresswayPostDao(getXpresswayPostDaoConfig, this);
        recentActivityDao = new RecentActivityDao(recentActivityDaoConfig, this);
        commentsDao = new CommentsDao(commentsDaoConfig, this);
        xpresswayDao = new XpresswayDao(xpresswayDaoConfig, this);
        awardDao = new AwardDao(awardDaoConfig, this);
        expossorDao = new ExpossorDao(expossorDaoConfig, this);
        currentOpinionDao = new CurrentOpinionDao(currentOpinionDaoConfig, this);
        pollResultDao = new PollResultDao(pollResultDaoConfig, this);
        bulletinCategoryDao = new BulletinCategoryDao(bulletinCategoryDaoConfig, this);
        recognitionGivenDao = new RecognitionGivenDao(recognitionGivenDaoConfig, this);
        recognitionRecievedDao = new RecognitionRecievedDao(recognitionRecievedDaoConfig, this);
        recognitionGivenListDao = new RecognitionGivenListDao(recognitionGivenListDaoConfig, this);
        recognitionRecievedListDao = new RecognitionRecievedListDao(recognitionRecievedListDaoConfig, this);
        celebrationMomentsDao = new CelebrationMomentsDao(celebrationMomentsDaoConfig, this);
        countRGDao = new CountRGDao(countRGDaoConfig, this);
        givenLikeDao = new GivenLikeDao(givenLikeDaoConfig, this);
        bulletinListDao = new BulletinListDao(bulletinListDaoConfig, this);
        srijanTOPCommentDao = new SrijanTOPCommentDao(srijanTOPCommentDaoConfig, this);
        clusterDao = new ClusterDao(clusterDaoConfig, this);
        gPWALLPOSTDao = new GPWALLPOSTDao(gPWALLPOSTDaoConfig, this);
        xPGPWALLPOSTDao = new XPGPWALLPOSTDao(xPGPWALLPOSTDaoConfig, this);

        registerDao(UserLoginInfo.class, userLoginInfoDao);
        registerDao(AllUserEvent.class, allUserEventDao);
        registerDao(UserWedding.class, userWeddingDao);
        registerDao(AllUsers.class, allUsersDao);
        registerDao(AllWebNotification.class, allWebNotificationDao);
        registerDao(GetMorePost.class, getMorePostDao);
        registerDao(GetXpresswayPost.class, getXpresswayPostDao);
        registerDao(RecentActivity.class, recentActivityDao);
        registerDao(Comments.class, commentsDao);
        registerDao(Xpressway.class, xpresswayDao);
        registerDao(Award.class, awardDao);
        registerDao(Expossor.class, expossorDao);
        registerDao(CurrentOpinion.class, currentOpinionDao);
        registerDao(PollResult.class, pollResultDao);
        registerDao(BulletinCategory.class, bulletinCategoryDao);
        registerDao(RecognitionGiven.class, recognitionGivenDao);
        registerDao(RecognitionRecieved.class, recognitionRecievedDao);
        registerDao(RecognitionGivenList.class, recognitionGivenListDao);
        registerDao(RecognitionRecievedList.class, recognitionRecievedListDao);
        registerDao(CelebrationMoments.class, celebrationMomentsDao);
        registerDao(CountRG.class, countRGDao);
        registerDao(GivenLike.class, givenLikeDao);
        registerDao(BulletinList.class, bulletinListDao);
        registerDao(SrijanTOPComment.class, srijanTOPCommentDao);
        registerDao(Cluster.class, clusterDao);
        registerDao(GPWALLPOST.class, gPWALLPOSTDao);
        registerDao(XPGPWALLPOST.class, xPGPWALLPOSTDao);
    }

    public void clear() {
        userLoginInfoDaoConfig.getIdentityScope().clear();
        allUserEventDaoConfig.getIdentityScope().clear();
        userWeddingDaoConfig.getIdentityScope().clear();
        allUsersDaoConfig.getIdentityScope().clear();
        allWebNotificationDaoConfig.getIdentityScope().clear();
        getMorePostDaoConfig.getIdentityScope().clear();
        getXpresswayPostDaoConfig.getIdentityScope().clear();
        recentActivityDaoConfig.getIdentityScope().clear();
        commentsDaoConfig.getIdentityScope().clear();
        xpresswayDaoConfig.getIdentityScope().clear();
        awardDaoConfig.getIdentityScope().clear();
        expossorDaoConfig.getIdentityScope().clear();
        currentOpinionDaoConfig.getIdentityScope().clear();
        pollResultDaoConfig.getIdentityScope().clear();
        bulletinCategoryDaoConfig.getIdentityScope().clear();
        recognitionGivenDaoConfig.getIdentityScope().clear();
        recognitionRecievedDaoConfig.getIdentityScope().clear();
        recognitionGivenListDaoConfig.getIdentityScope().clear();
        recognitionRecievedListDaoConfig.getIdentityScope().clear();
        celebrationMomentsDaoConfig.getIdentityScope().clear();
        countRGDaoConfig.getIdentityScope().clear();
        givenLikeDaoConfig.getIdentityScope().clear();
        bulletinListDaoConfig.getIdentityScope().clear();
        srijanTOPCommentDaoConfig.getIdentityScope().clear();
        clusterDaoConfig.getIdentityScope().clear();
        gPWALLPOSTDaoConfig.getIdentityScope().clear();
        xPGPWALLPOSTDaoConfig.getIdentityScope().clear();
    }

    public UserLoginInfoDao getUserLoginInfoDao() {
        return userLoginInfoDao;
    }

    public AllUserEventDao getAllUserEventDao() {
        return allUserEventDao;
    }

    public UserWeddingDao getUserWeddingDao() {
        return userWeddingDao;
    }

    public AllUsersDao getAllUsersDao() {
        return allUsersDao;
    }

    public AllWebNotificationDao getAllWebNotificationDao() {
        return allWebNotificationDao;
    }

    public GetMorePostDao getGetMorePostDao() {
        return getMorePostDao;
    }

    public GetXpresswayPostDao getGetXpresswayPostDao() {
        return getXpresswayPostDao;
    }

    public RecentActivityDao getRecentActivityDao() {
        return recentActivityDao;
    }

    public CommentsDao getCommentsDao() {
        return commentsDao;
    }

    public XpresswayDao getXpresswayDao() {
        return xpresswayDao;
    }

    public AwardDao getAwardDao() {
        return awardDao;
    }

    public ExpossorDao getExpossorDao() {
        return expossorDao;
    }

    public CurrentOpinionDao getCurrentOpinionDao() {
        return currentOpinionDao;
    }

    public PollResultDao getPollResultDao() {
        return pollResultDao;
    }

    public BulletinCategoryDao getBulletinCategoryDao() {
        return bulletinCategoryDao;
    }

    public RecognitionGivenDao getRecognitionGivenDao() {
        return recognitionGivenDao;
    }

    public RecognitionRecievedDao getRecognitionRecievedDao() {
        return recognitionRecievedDao;
    }

    public RecognitionGivenListDao getRecognitionGivenListDao() {
        return recognitionGivenListDao;
    }

    public RecognitionRecievedListDao getRecognitionRecievedListDao() {
        return recognitionRecievedListDao;
    }

    public CelebrationMomentsDao getCelebrationMomentsDao() {
        return celebrationMomentsDao;
    }

    public CountRGDao getCountRGDao() {
        return countRGDao;
    }

    public GivenLikeDao getGivenLikeDao() {
        return givenLikeDao;
    }

    public BulletinListDao getBulletinListDao() {
        return bulletinListDao;
    }

    public SrijanTOPCommentDao getSrijanTOPCommentDao() {
        return srijanTOPCommentDao;
    }

    public ClusterDao getClusterDao() {
        return clusterDao;
    }

    public GPWALLPOSTDao getGPWALLPOSTDao() {
        return gPWALLPOSTDao;
    }

    public XPGPWALLPOSTDao getXPGPWALLPOSTDao() {
        return xPGPWALLPOSTDao;
    }

}
