package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EXPOSSOR".
 */
public class Expossor {

    private String sno;
    private String xpressor_id;
    private String xpressor_text;
    private String xpressor_rmtxt;
    /** Not-null value. */
    private String awardID;

    public Expossor() {
    }

    public Expossor(String sno, String xpressor_id, String xpressor_text, String xpressor_rmtxt, String awardID) {
        this.sno = sno;
        this.xpressor_id = xpressor_id;
        this.xpressor_text = xpressor_text;
        this.xpressor_rmtxt = xpressor_rmtxt;
        this.awardID = awardID;
    }

    public String getSno() {
        return sno;
    }

    public void setSno(String sno) {
        this.sno = sno;
    }

    public String getXpressor_id() {
        return xpressor_id;
    }

    public void setXpressor_id(String xpressor_id) {
        this.xpressor_id = xpressor_id;
    }

    public String getXpressor_text() {
        return xpressor_text;
    }

    public void setXpressor_text(String xpressor_text) {
        this.xpressor_text = xpressor_text;
    }

    public String getXpressor_rmtxt() {
        return xpressor_rmtxt;
    }

    public void setXpressor_rmtxt(String xpressor_rmtxt) {
        this.xpressor_rmtxt = xpressor_rmtxt;
    }

    /** Not-null value. */
    public String getAwardID() {
        return awardID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAwardID(String awardID) {
        this.awardID = awardID;
    }

}
