package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GET_MORE_POST".
 */
public class GetMorePost {

    private String userid;
    private String nominator_name;
    private String nominator_designation;
    private String nominator_location;
    private String nominator_imageurl;
    private String nominee_name;
    private String nominee_designation;
    private String nominee_location;
    private String nominee_imageurl;
    private String title;
    private String description;
    private String details;
    private String challengesfaced;
    private String is_story;
    private String recognise_date;
    private String event_date;
    private String type;
    private String url;
    private String icon;
    private String count;
    private String likes;
    private String comments;
    private String ulikes;
    private String ucomments;
    private String recognition_id;
    private String nominee;
    private String subject;
    private String isxpress;
    private String awardid;
    private String date;
    private String isNomineeDonor;
    private String isNominatorDonar;
    private String taguserid;
    private String tagcount;

    public GetMorePost() {
    }

    public GetMorePost(String recognition_id) {
        this.recognition_id = recognition_id;
    }

    public GetMorePost(String userid, String nominator_name, String nominator_designation, String nominator_location, String nominator_imageurl, String nominee_name, String nominee_designation, String nominee_location, String nominee_imageurl, String title, String description, String details, String challengesfaced, String is_story, String recognise_date, String event_date, String type, String url, String icon, String count, String likes, String comments, String ulikes, String ucomments, String recognition_id, String nominee, String subject, String isxpress, String awardid, String date, String isNomineeDonor, String isNominatorDonar, String taguserid, String tagcount) {
        this.userid = userid;
        this.nominator_name = nominator_name;
        this.nominator_designation = nominator_designation;
        this.nominator_location = nominator_location;
        this.nominator_imageurl = nominator_imageurl;
        this.nominee_name = nominee_name;
        this.nominee_designation = nominee_designation;
        this.nominee_location = nominee_location;
        this.nominee_imageurl = nominee_imageurl;
        this.title = title;
        this.description = description;
        this.details = details;
        this.challengesfaced = challengesfaced;
        this.is_story = is_story;
        this.recognise_date = recognise_date;
        this.event_date = event_date;
        this.type = type;
        this.url = url;
        this.icon = icon;
        this.count = count;
        this.likes = likes;
        this.comments = comments;
        this.ulikes = ulikes;
        this.ucomments = ucomments;
        this.recognition_id = recognition_id;
        this.nominee = nominee;
        this.subject = subject;
        this.isxpress = isxpress;
        this.awardid = awardid;
        this.date = date;
        this.isNomineeDonor = isNomineeDonor;
        this.isNominatorDonar = isNominatorDonar;
        this.taguserid = taguserid;
        this.tagcount = tagcount;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getNominator_name() {
        return nominator_name;
    }

    public void setNominator_name(String nominator_name) {
        this.nominator_name = nominator_name;
    }

    public String getNominator_designation() {
        return nominator_designation;
    }

    public void setNominator_designation(String nominator_designation) {
        this.nominator_designation = nominator_designation;
    }

    public String getNominator_location() {
        return nominator_location;
    }

    public void setNominator_location(String nominator_location) {
        this.nominator_location = nominator_location;
    }

    public String getNominator_imageurl() {
        return nominator_imageurl;
    }

    public void setNominator_imageurl(String nominator_imageurl) {
        this.nominator_imageurl = nominator_imageurl;
    }

    public String getNominee_name() {
        return nominee_name;
    }

    public void setNominee_name(String nominee_name) {
        this.nominee_name = nominee_name;
    }

    public String getNominee_designation() {
        return nominee_designation;
    }

    public void setNominee_designation(String nominee_designation) {
        this.nominee_designation = nominee_designation;
    }

    public String getNominee_location() {
        return nominee_location;
    }

    public void setNominee_location(String nominee_location) {
        this.nominee_location = nominee_location;
    }

    public String getNominee_imageurl() {
        return nominee_imageurl;
    }

    public void setNominee_imageurl(String nominee_imageurl) {
        this.nominee_imageurl = nominee_imageurl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public String getChallengesfaced() {
        return challengesfaced;
    }

    public void setChallengesfaced(String challengesfaced) {
        this.challengesfaced = challengesfaced;
    }

    public String getIs_story() {
        return is_story;
    }

    public void setIs_story(String is_story) {
        this.is_story = is_story;
    }

    public String getRecognise_date() {
        return recognise_date;
    }

    public void setRecognise_date(String recognise_date) {
        this.recognise_date = recognise_date;
    }

    public String getEvent_date() {
        return event_date;
    }

    public void setEvent_date(String event_date) {
        this.event_date = event_date;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getLikes() {
        return likes;
    }

    public void setLikes(String likes) {
        this.likes = likes;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getUlikes() {
        return ulikes;
    }

    public void setUlikes(String ulikes) {
        this.ulikes = ulikes;
    }

    public String getUcomments() {
        return ucomments;
    }

    public void setUcomments(String ucomments) {
        this.ucomments = ucomments;
    }

    public String getRecognition_id() {
        return recognition_id;
    }

    public void setRecognition_id(String recognition_id) {
        this.recognition_id = recognition_id;
    }

    public String getNominee() {
        return nominee;
    }

    public void setNominee(String nominee) {
        this.nominee = nominee;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getIsxpress() {
        return isxpress;
    }

    public void setIsxpress(String isxpress) {
        this.isxpress = isxpress;
    }

    public String getAwardid() {
        return awardid;
    }

    public void setAwardid(String awardid) {
        this.awardid = awardid;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getIsNomineeDonor() {
        return isNomineeDonor;
    }

    public void setIsNomineeDonor(String isNomineeDonor) {
        this.isNomineeDonor = isNomineeDonor;
    }

    public String getIsNominatorDonar() {
        return isNominatorDonar;
    }

    public void setIsNominatorDonar(String isNominatorDonar) {
        this.isNominatorDonar = isNominatorDonar;
    }

    public String getTaguserid() {
        return taguserid;
    }

    public void setTaguserid(String taguserid) {
        this.taguserid = taguserid;
    }

    public String getTagcount() {
        return tagcount;
    }

    public void setTagcount(String tagcount) {
        this.tagcount = tagcount;
    }

}
