package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GIVEN_LIKE".
 */
public class GivenLike {

    private String recognition_id;
    private String userid;
    private String userName;
    private String designation;
    private String department;
    private String location;
    private String imageurl;

    public GivenLike() {
    }

    public GivenLike(String recognition_id, String userid, String userName, String designation, String department, String location, String imageurl) {
        this.recognition_id = recognition_id;
        this.userid = userid;
        this.userName = userName;
        this.designation = designation;
        this.department = department;
        this.location = location;
        this.imageurl = imageurl;
    }

    public String getRecognition_id() {
        return recognition_id;
    }

    public void setRecognition_id(String recognition_id) {
        this.recognition_id = recognition_id;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getImageurl() {
        return imageurl;
    }

    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

}
