package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "POLL_RESULT".
 */
public class PollResult {

    private String opinionid;
    private String question;
    private String answertype;
    private String enddate;
    private String isactive;
    private String agree_perc;
    private String disagree_perc;
    private String cantsay_perc;
    private String status;

    public PollResult() {
    }

    public PollResult(String opinionid, String question, String answertype, String enddate, String isactive, String agree_perc, String disagree_perc, String cantsay_perc, String status) {
        this.opinionid = opinionid;
        this.question = question;
        this.answertype = answertype;
        this.enddate = enddate;
        this.isactive = isactive;
        this.agree_perc = agree_perc;
        this.disagree_perc = disagree_perc;
        this.cantsay_perc = cantsay_perc;
        this.status = status;
    }

    public String getOpinionid() {
        return opinionid;
    }

    public void setOpinionid(String opinionid) {
        this.opinionid = opinionid;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getAnswertype() {
        return answertype;
    }

    public void setAnswertype(String answertype) {
        this.answertype = answertype;
    }

    public String getEnddate() {
        return enddate;
    }

    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }

    public String getIsactive() {
        return isactive;
    }

    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    public String getAgree_perc() {
        return agree_perc;
    }

    public void setAgree_perc(String agree_perc) {
        this.agree_perc = agree_perc;
    }

    public String getDisagree_perc() {
        return disagree_perc;
    }

    public void setDisagree_perc(String disagree_perc) {
        this.disagree_perc = disagree_perc;
    }

    public String getCantsay_perc() {
        return cantsay_perc;
    }

    public void setCantsay_perc(String cantsay_perc) {
        this.cantsay_perc = cantsay_perc;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
