package db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "RECENT_ACTIVITY".
 */
public class RecentActivityDao extends AbstractDao<RecentActivity, Void> {

    public static final String TABLENAME = "RECENT_ACTIVITY";

    /**
     * Properties of entity RecentActivity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Nominator_name = new Property(0, String.class, "nominator_name", false, "NOMINATOR_NAME");
        public final static Property Nominee_name = new Property(1, String.class, "nominee_name", false, "NOMINEE_NAME");
        public final static Property Recognise_date = new Property(2, String.class, "recognise_date", false, "RECOGNISE_DATE");
        public final static Property Recognition_name = new Property(3, String.class, "recognition_name", false, "RECOGNITION_NAME");
        public final static Property Is_story = new Property(4, String.class, "is_story", false, "IS_STORY");
        public final static Property Count = new Property(5, String.class, "count", false, "COUNT");
        public final static Property Recognition_id = new Property(6, String.class, "recognition_id", false, "RECOGNITION_ID");
        public final static Property Nominee = new Property(7, String.class, "nominee", false, "NOMINEE");
        public final static Property Isxpress = new Property(8, String.class, "isxpress", false, "ISXPRESS");
        public final static Property Award = new Property(9, String.class, "award", false, "AWARD");
        public final static Property Type_view = new Property(10, String.class, "type_view", false, "TYPE_VIEW");
    }

    ;


    public RecentActivityDao(DaoConfig config) {
        super(config);
    }

    public RecentActivityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECENT_ACTIVITY\" (" + //
                "\"NOMINATOR_NAME\" TEXT," + // 0: nominator_name
                "\"NOMINEE_NAME\" TEXT," + // 1: nominee_name
                "\"RECOGNISE_DATE\" TEXT," + // 2: recognise_date
                "\"RECOGNITION_NAME\" TEXT," + // 3: recognition_name
                "\"IS_STORY\" TEXT," + // 4: is_story
                "\"COUNT\" TEXT," + // 5: count
                "\"RECOGNITION_ID\" TEXT," + // 6: recognition_id
                "\"NOMINEE\" TEXT," + // 7: nominee
                "\"ISXPRESS\" TEXT," + // 8: isxpress
                "\"AWARD\" TEXT," + // 9: award
                "\"TYPE_VIEW\" TEXT);"); // 10: type_view
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECENT_ACTIVITY\"";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, RecentActivity entity) {
        stmt.clearBindings();

        String nominator_name = entity.getNominator_name();
        if (nominator_name != null) {
            stmt.bindString(1, nominator_name);
        }

        String nominee_name = entity.getNominee_name();
        if (nominee_name != null) {
            stmt.bindString(2, nominee_name);
        }

        String recognise_date = entity.getRecognise_date();
        if (recognise_date != null) {
            stmt.bindString(3, recognise_date);
        }

        String recognition_name = entity.getRecognition_name();
        if (recognition_name != null) {
            stmt.bindString(4, recognition_name);
        }

        String is_story = entity.getIs_story();
        if (is_story != null) {
            stmt.bindString(5, is_story);
        }

        String count = entity.getCount();
        if (count != null) {
            stmt.bindString(6, count);
        }

        String recognition_id = entity.getRecognition_id();
        if (recognition_id != null) {
            stmt.bindString(7, recognition_id);
        }

        String nominee = entity.getNominee();
        if (nominee != null) {
            stmt.bindString(8, nominee);
        }

        String isxpress = entity.getIsxpress();
        if (isxpress != null) {
            stmt.bindString(9, isxpress);
        }

        String award = entity.getAward();
        if (award != null) {
            stmt.bindString(10, award);
        }

        String type_view = entity.getType_view();
        if (type_view != null) {
            stmt.bindString(11, type_view);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }

    /**
     * @inheritdoc
     */
    @Override
    public RecentActivity readEntity(Cursor cursor, int offset) {
        RecentActivity entity = new RecentActivity( //
                cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // nominator_name
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nominee_name
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // recognise_date
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // recognition_name
                cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // is_story
                cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // count
                cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // recognition_id
                cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // nominee
                cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // isxpress
                cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // award
                cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // type_view
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, RecentActivity entity, int offset) {
        entity.setNominator_name(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setNominee_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRecognise_date(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRecognition_name(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIs_story(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCount(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRecognition_id(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setNominee(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIsxpress(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setAward(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setType_view(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Void updateKeyAfterInsert(RecentActivity entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Void getKey(RecentActivity entity) {
        return null;
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
