package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECENT_ACTIVITY".
 */
public class RecentActivity {

    private String nominator_name;
    private String nominee_name;
    private String recognise_date;
    private String recognition_name;
    private String is_story;
    private String count;
    private String recognition_id;
    private String nominee;
    private String isxpress;
    private String award;
    private String type_view;

    public RecentActivity() {
    }

    public RecentActivity(String nominator_name, String nominee_name, String recognise_date, String recognition_name, String is_story, String count, String recognition_id, String nominee, String isxpress, String award, String type_view) {
        this.nominator_name = nominator_name;
        this.nominee_name = nominee_name;
        this.recognise_date = recognise_date;
        this.recognition_name = recognition_name;
        this.is_story = is_story;
        this.count = count;
        this.recognition_id = recognition_id;
        this.nominee = nominee;
        this.isxpress = isxpress;
        this.award = award;
        this.type_view = type_view;
    }

    public String getNominator_name() {
        return nominator_name;
    }

    public void setNominator_name(String nominator_name) {
        this.nominator_name = nominator_name;
    }

    public String getNominee_name() {
        return nominee_name;
    }

    public void setNominee_name(String nominee_name) {
        this.nominee_name = nominee_name;
    }

    public String getRecognise_date() {
        return recognise_date;
    }

    public void setRecognise_date(String recognise_date) {
        this.recognise_date = recognise_date;
    }

    public String getRecognition_name() {
        return recognition_name;
    }

    public void setRecognition_name(String recognition_name) {
        this.recognition_name = recognition_name;
    }

    public String getIs_story() {
        return is_story;
    }

    public void setIs_story(String is_story) {
        this.is_story = is_story;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getRecognition_id() {
        return recognition_id;
    }

    public void setRecognition_id(String recognition_id) {
        this.recognition_id = recognition_id;
    }

    public String getNominee() {
        return nominee;
    }

    public void setNominee(String nominee) {
        this.nominee = nominee;
    }

    public String getIsxpress() {
        return isxpress;
    }

    public void setIsxpress(String isxpress) {
        this.isxpress = isxpress;
    }

    public String getAward() {
        return award;
    }

    public void setAward(String award) {
        this.award = award;
    }

    public String getType_view() {
        return type_view;
    }

    public void setType_view(String type_view) {
        this.type_view = type_view;
    }

}
