package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECOGNITION_RECIEVED".
 */
public class RecognitionRecieved {

    private String awardid;
    private String awardName;
    private String count;
    private String total;

    public RecognitionRecieved() {
    }

    public RecognitionRecieved(String awardid, String awardName, String count, String total) {
        this.awardid = awardid;
        this.awardName = awardName;
        this.count = count;
        this.total = total;
    }

    public String getAwardid() {
        return awardid;
    }

    public void setAwardid(String awardid) {
        this.awardid = awardid;
    }

    public String getAwardName() {
        return awardName;
    }

    public void setAwardName(String awardName) {
        this.awardName = awardName;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getTotal() {
        return total;
    }

    public void setTotal(String total) {
        this.total = total;
    }

}
