package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SRIJAN_TOPCOMMENT".
 */
public class SrijanTOPComment {

    private String policyid;
    private String policyname;
    private String policynamedisplayvalue;
    private String usercommentdisplayvalue;
    private String commentdatedisplayvalue;
    private String commenttimedisplayvalue;
    private String commentuserid;
    private String commentusername;
    private String commentuserdepartment;
    private String commentuserprofilepic;
    private String commentlevel;
    private String parentcommentid;
    private String usercomment;
    private String taguser;
    private String childcommentid;

    public SrijanTOPComment() {
    }

    public SrijanTOPComment(String policyid, String policyname, String policynamedisplayvalue, String usercommentdisplayvalue, String commentdatedisplayvalue, String commenttimedisplayvalue, String commentuserid, String commentusername, String commentuserdepartment, String commentuserprofilepic, String commentlevel, String parentcommentid, String usercomment, String taguser, String childcommentid) {
        this.policyid = policyid;
        this.policyname = policyname;
        this.policynamedisplayvalue = policynamedisplayvalue;
        this.usercommentdisplayvalue = usercommentdisplayvalue;
        this.commentdatedisplayvalue = commentdatedisplayvalue;
        this.commenttimedisplayvalue = commenttimedisplayvalue;
        this.commentuserid = commentuserid;
        this.commentusername = commentusername;
        this.commentuserdepartment = commentuserdepartment;
        this.commentuserprofilepic = commentuserprofilepic;
        this.commentlevel = commentlevel;
        this.parentcommentid = parentcommentid;
        this.usercomment = usercomment;
        this.taguser = taguser;
        this.childcommentid = childcommentid;
    }

    public String getPolicyid() {
        return policyid;
    }

    public void setPolicyid(String policyid) {
        this.policyid = policyid;
    }

    public String getPolicyname() {
        return policyname;
    }

    public void setPolicyname(String policyname) {
        this.policyname = policyname;
    }

    public String getPolicynamedisplayvalue() {
        return policynamedisplayvalue;
    }

    public void setPolicynamedisplayvalue(String policynamedisplayvalue) {
        this.policynamedisplayvalue = policynamedisplayvalue;
    }

    public String getUsercommentdisplayvalue() {
        return usercommentdisplayvalue;
    }

    public void setUsercommentdisplayvalue(String usercommentdisplayvalue) {
        this.usercommentdisplayvalue = usercommentdisplayvalue;
    }

    public String getCommentdatedisplayvalue() {
        return commentdatedisplayvalue;
    }

    public void setCommentdatedisplayvalue(String commentdatedisplayvalue) {
        this.commentdatedisplayvalue = commentdatedisplayvalue;
    }

    public String getCommenttimedisplayvalue() {
        return commenttimedisplayvalue;
    }

    public void setCommenttimedisplayvalue(String commenttimedisplayvalue) {
        this.commenttimedisplayvalue = commenttimedisplayvalue;
    }

    public String getCommentuserid() {
        return commentuserid;
    }

    public void setCommentuserid(String commentuserid) {
        this.commentuserid = commentuserid;
    }

    public String getCommentusername() {
        return commentusername;
    }

    public void setCommentusername(String commentusername) {
        this.commentusername = commentusername;
    }

    public String getCommentuserdepartment() {
        return commentuserdepartment;
    }

    public void setCommentuserdepartment(String commentuserdepartment) {
        this.commentuserdepartment = commentuserdepartment;
    }

    public String getCommentuserprofilepic() {
        return commentuserprofilepic;
    }

    public void setCommentuserprofilepic(String commentuserprofilepic) {
        this.commentuserprofilepic = commentuserprofilepic;
    }

    public String getCommentlevel() {
        return commentlevel;
    }

    public void setCommentlevel(String commentlevel) {
        this.commentlevel = commentlevel;
    }

    public String getParentcommentid() {
        return parentcommentid;
    }

    public void setParentcommentid(String parentcommentid) {
        this.parentcommentid = parentcommentid;
    }

    public String getUsercomment() {
        return usercomment;
    }

    public void setUsercomment(String usercomment) {
        this.usercomment = usercomment;
    }

    public String getTaguser() {
        return taguser;
    }

    public void setTaguser(String taguser) {
        this.taguser = taguser;
    }

    public String getChildcommentid() {
        return childcommentid;
    }

    public void setChildcommentid(String childcommentid) {
        this.childcommentid = childcommentid;
    }

}
