package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_LOGIN_INFO".
 */
public class UserLoginInfo {

    private String userid;
    private String empno;
    private String name;
    private String username;
    private String dob;
    private String location;
    private String role;
    private String department;
    private String designation;
    private String quote;
    private String hobbies;
    private String imageurl;
    private String company;
    private String experience;
    private String is_admin;
    private String emailId;
    private String reg_mngr;
    private String post_xpress;
    private String rrecognition;
    private String grecognition;
    private String isdonor;
    private String isrijan;

    public UserLoginInfo() {
    }

    public UserLoginInfo(String userid) {
        this.userid = userid;
    }

    public UserLoginInfo(String userid, String empno, String name, String username, String dob, String location, String role, String department, String designation, String quote, String hobbies, String imageurl, String company, String experience, String is_admin, String emailId, String reg_mngr, String post_xpress, String rrecognition, String grecognition, String isdonor, String isrijan) {
        this.userid = userid;
        this.empno = empno;
        this.name = name;
        this.username = username;
        this.dob = dob;
        this.location = location;
        this.role = role;
        this.department = department;
        this.designation = designation;
        this.quote = quote;
        this.hobbies = hobbies;
        this.imageurl = imageurl;
        this.company = company;
        this.experience = experience;
        this.is_admin = is_admin;
        this.emailId = emailId;
        this.reg_mngr = reg_mngr;
        this.post_xpress = post_xpress;
        this.rrecognition = rrecognition;
        this.grecognition = grecognition;
        this.isdonor = isdonor;
        this.isrijan = isrijan;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getEmpno() {
        return empno;
    }

    public void setEmpno(String empno) {
        this.empno = empno;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getDob() {
        return dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    public String getQuote() {
        return quote;
    }

    public void setQuote(String quote) {
        this.quote = quote;
    }

    public String getHobbies() {
        return hobbies;
    }

    public void setHobbies(String hobbies) {
        this.hobbies = hobbies;
    }

    public String getImageurl() {
        return imageurl;
    }

    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getExperience() {
        return experience;
    }

    public void setExperience(String experience) {
        this.experience = experience;
    }

    public String getIs_admin() {
        return is_admin;
    }

    public void setIs_admin(String is_admin) {
        this.is_admin = is_admin;
    }

    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    public String getReg_mngr() {
        return reg_mngr;
    }

    public void setReg_mngr(String reg_mngr) {
        this.reg_mngr = reg_mngr;
    }

    public String getPost_xpress() {
        return post_xpress;
    }

    public void setPost_xpress(String post_xpress) {
        this.post_xpress = post_xpress;
    }

    public String getRrecognition() {
        return rrecognition;
    }

    public void setRrecognition(String rrecognition) {
        this.rrecognition = rrecognition;
    }

    public String getGrecognition() {
        return grecognition;
    }

    public void setGrecognition(String grecognition) {
        this.grecognition = grecognition;
    }

    public String getIsdonor() {
        return isdonor;
    }

    public void setIsdonor(String isdonor) {
        this.isdonor = isdonor;
    }

    public String getIsrijan() {
        return isrijan;
    }

    public void setIsrijan(String isrijan) {
        this.isrijan = isrijan;
    }

}
