package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_WEDDING".
 */
public class UserWedding {

    private String userid;
    private String name;
    private String dob;
    private String doj;
    private String dow;
    private String image_url;
    private String issubcribe;
    private String isbirthday_subscribe;
    private String iswork_subscribe;
    private String iswedding_subscribe;

    public UserWedding() {
    }

    public UserWedding(String userid, String name, String dob, String doj, String dow, String image_url, String issubcribe, String isbirthday_subscribe, String iswork_subscribe, String iswedding_subscribe) {
        this.userid = userid;
        this.name = name;
        this.dob = dob;
        this.doj = doj;
        this.dow = dow;
        this.image_url = image_url;
        this.issubcribe = issubcribe;
        this.isbirthday_subscribe = isbirthday_subscribe;
        this.iswork_subscribe = iswork_subscribe;
        this.iswedding_subscribe = iswedding_subscribe;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDob() {
        return dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public String getDoj() {
        return doj;
    }

    public void setDoj(String doj) {
        this.doj = doj;
    }

    public String getDow() {
        return dow;
    }

    public void setDow(String dow) {
        this.dow = dow;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public String getIssubcribe() {
        return issubcribe;
    }

    public void setIssubcribe(String issubcribe) {
        this.issubcribe = issubcribe;
    }

    public String getIsbirthday_subscribe() {
        return isbirthday_subscribe;
    }

    public void setIsbirthday_subscribe(String isbirthday_subscribe) {
        this.isbirthday_subscribe = isbirthday_subscribe;
    }

    public String getIswork_subscribe() {
        return iswork_subscribe;
    }

    public void setIswork_subscribe(String iswork_subscribe) {
        this.iswork_subscribe = iswork_subscribe;
    }

    public String getIswedding_subscribe() {
        return iswedding_subscribe;
    }

    public void setIswedding_subscribe(String iswedding_subscribe) {
        this.iswedding_subscribe = iswedding_subscribe;
    }

}
