package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "XPGPWALLPOST".
 */
public class XPGPWALLPOST {

    private String gpostid;
    private String gid;
    private String details;
    private String type;
    private String userid;
    private String event_date;
    private String isxpress;
    private String taguserid;
    private String tabusername;
    private String nominee_imageurl;
    private String nominee_designation;
    private String nominator_name;
    private String likes;
    private String comments;
    private String tagcount;
    private String subject;
    private String url;
    private String devicetype;
    private String vcount;
    private String themeid;

    public XPGPWALLPOST() {
    }

    public XPGPWALLPOST(String gpostid) {
        this.gpostid = gpostid;
    }

    public XPGPWALLPOST(String gpostid, String gid, String details, String type, String userid, String event_date, String isxpress, String taguserid, String tabusername, String nominee_imageurl, String nominee_designation, String nominator_name, String likes, String comments, String tagcount, String subject, String url, String devicetype, String vcount, String themeid) {
        this.gpostid = gpostid;
        this.gid = gid;
        this.details = details;
        this.type = type;
        this.userid = userid;
        this.event_date = event_date;
        this.isxpress = isxpress;
        this.taguserid = taguserid;
        this.tabusername = tabusername;
        this.nominee_imageurl = nominee_imageurl;
        this.nominee_designation = nominee_designation;
        this.nominator_name = nominator_name;
        this.likes = likes;
        this.comments = comments;
        this.tagcount = tagcount;
        this.subject = subject;
        this.url = url;
        this.devicetype = devicetype;
        this.vcount = vcount;
        this.themeid = themeid;
    }

    public String getGpostid() {
        return gpostid;
    }

    public void setGpostid(String gpostid) {
        this.gpostid = gpostid;
    }

    public String getGid() {
        return gid;
    }

    public void setGid(String gid) {
        this.gid = gid;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getEvent_date() {
        return event_date;
    }

    public void setEvent_date(String event_date) {
        this.event_date = event_date;
    }

    public String getIsxpress() {
        return isxpress;
    }

    public void setIsxpress(String isxpress) {
        this.isxpress = isxpress;
    }

    public String getTaguserid() {
        return taguserid;
    }

    public void setTaguserid(String taguserid) {
        this.taguserid = taguserid;
    }

    public String getTabusername() {
        return tabusername;
    }

    public void setTabusername(String tabusername) {
        this.tabusername = tabusername;
    }

    public String getNominee_imageurl() {
        return nominee_imageurl;
    }

    public void setNominee_imageurl(String nominee_imageurl) {
        this.nominee_imageurl = nominee_imageurl;
    }

    public String getNominee_designation() {
        return nominee_designation;
    }

    public void setNominee_designation(String nominee_designation) {
        this.nominee_designation = nominee_designation;
    }

    public String getNominator_name() {
        return nominator_name;
    }

    public void setNominator_name(String nominator_name) {
        this.nominator_name = nominator_name;
    }

    public String getLikes() {
        return likes;
    }

    public void setLikes(String likes) {
        this.likes = likes;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getTagcount() {
        return tagcount;
    }

    public void setTagcount(String tagcount) {
        this.tagcount = tagcount;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDevicetype() {
        return devicetype;
    }

    public void setDevicetype(String devicetype) {
        this.devicetype = devicetype;
    }

    public String getVcount() {
        return vcount;
    }

    public void setVcount(String vcount) {
        this.vcount = vcount;
    }

    public String getThemeid() {
        return themeid;
    }

    public void setThemeid(String themeid) {
        this.themeid = themeid;
    }

}
