package db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "XPRESSWAY".
 */
public class Xpressway {

    private String recognition_id;
    private String nominator_name;
    private String subject;
    private String isstory;
    private String nominee;
    private String other;
    private String award;
    private String recognise_date;
    private String image_url;

    public Xpressway() {
    }

    public Xpressway(String recognition_id, String nominator_name, String subject, String isstory, String nominee, String other, String award, String recognise_date, String image_url) {
        this.recognition_id = recognition_id;
        this.nominator_name = nominator_name;
        this.subject = subject;
        this.isstory = isstory;
        this.nominee = nominee;
        this.other = other;
        this.award = award;
        this.recognise_date = recognise_date;
        this.image_url = image_url;
    }

    public String getRecognition_id() {
        return recognition_id;
    }

    public void setRecognition_id(String recognition_id) {
        this.recognition_id = recognition_id;
    }

    public String getNominator_name() {
        return nominator_name;
    }

    public void setNominator_name(String nominator_name) {
        this.nominator_name = nominator_name;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getIsstory() {
        return isstory;
    }

    public void setIsstory(String isstory) {
        this.isstory = isstory;
    }

    public String getNominee() {
        return nominee;
    }

    public void setNominee(String nominee) {
        this.nominee = nominee;
    }

    public String getOther() {
        return other;
    }

    public void setOther(String other) {
        this.other = other;
    }

    public String getAward() {
        return award;
    }

    public void setAward(String award) {
        this.award = award;
    }

    public String getRecognise_date() {
        return recognise_date;
    }

    public void setRecognise_date(String recognise_date) {
        this.recognise_date = recognise_date;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

}
